#!/usr/bin/env php
<?php

define('UPSTREAM_REPOSITORY', 'https://github.com/drupal/drupal');
define('UPSTREAM_DIRECTORY', 'upstream');
define('DOWNSTREAM_REPOSITORY', exec('git config --get remote.origin.url'));

exec('git ls-remote --tags ' . UPSTREAM_REPOSITORY, $upstream_tags);
exec('git ls-remote --tags ' . DOWNSTREAM_REPOSITORY, $downstream_tags);

$blacklist = array(
  '8.0.0-alpha14',
  '8.0.0-alpha15',
  '8.0.0-beta1',
  '8.0.0-beta2',
  '8.0.0-beta3',
  '8.0.0-beta4',
  '8.0.0-beta5',
);

function filter_valid_tags($upstream_tags, $blacklist) {
  $tags = array();
  foreach ($upstream_tags as $tag) {
    preg_match('/refs\/tags\/(8\.0\.[0-9]+.*)/', $tag, $value);
    if (isset($value[1]) && !in_array($value[1], $blacklist)) {
      $tags[] = $value[1];
    }
  }
  return $tags;
}

$upstream_tags = filter_valid_tags($upstream_tags, $blacklist);
$downstream_tags = filter_valid_tags($downstream_tags, $blacklist);

// Tags thats are not in the downstream repo.
$tags = array_diff($upstream_tags, $downstream_tags);

passthru('./subtree-split fetch');
foreach ($tags as $tag) {
  passthru('./subtree-split push tag ' . escapeshellarg($tag));
}

